const cities = [
  { id: 1, label: "Takahata" },
  { id: 2, label: "Condoroma" },
  { id: 3, label: "Dolní Kounice" },
  { id: 4, label: "Weifen" },
  { id: 5, label: "Were Īlu" },
  { id: 6, label: "Gyigang" },
  { id: 7, label: "Calubcub Dos" },
  { id: 8, label: "Sembalunbumbung" },
  { id: 9, label: "Asímion" },
  { id: 10, label: "Prupuh" },
  { id: 11, label: "Yamkino" },
  { id: 12, label: "Lüfeng" },
  { id: 13, label: "Huangshi" },
  { id: 14, label: "Balpyk Bī" },
  { id: 15, label: "Fīrūzābād" },
  { id: 16, label: "Lisków" },
  { id: 17, label: "Sayaxché" },
  { id: 18, label: "Jiangya" },
  { id: 19, label: "Filiatrá" },
  { id: 20, label: "Xinxu" },
  { id: 21, label: "Tyresö" },
  { id: 22, label: "Yaguajay" },
  { id: 23, label: "Taunoa" },
  { id: 24, label: "Andrijaševci" },
  { id: 25, label: "Carcassonne" },
  { id: 26, label: "Muritiba" },
  { id: 27, label: "Coaraci" },
  { id: 28, label: "Västerås" },
  { id: 29, label: "La Guama" },
  { id: 30, label: "Ventspils" },
  { id: 31, label: "Sogati" },
  { id: 32, label: "Kinzan" },
  { id: 33, label: "Salacgrīva" },
  { id: 34, label: "Guantánamo" },
  { id: 35, label: "Liudu" },
  { id: 36, label: "Fuding" },
  { id: 37, label: "Bifeng" },
  { id: 38, label: "Kuta" },
  { id: 39, label: "Yunxian Chengguanzhen" },
  { id: 40, label: "Chapimarca" },
  { id: 41, label: "Santo Antônio do Amparo" },
  { id: 42, label: "Shanghu" },
  { id: 43, label: "Calçada" },
  { id: 44, label: "Zopilotepe" },
  { id: 45, label: "Rzozów" },
  { id: 46, label: "Yupiltepeque" },
  { id: 47, label: "Henglu" },
  { id: 48, label: "Narva" },
  { id: 49, label: "Mambulo" },
  { id: 50, label: "Santa Cruz del Quiché" },
];

export default cities;
